title: Solanum IRCd
lang: en_UK
# email: your-email@example.com
description: >-
  Solanum is the upcoming IRCd that's being shepherded on by a collaboration of
  Libera and OFTC staff.
url: https://solanum.chat
github_username: solanum-ircd
logo: /img/solanum.optimised.svg

paginate: 10
paginate_path: "/news/page:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "spec"
    values:
      layout: page
  - scope:
      path: ""
      type: "doc"
    values:
      layout: page

collections:
  spec:
    output: true
    permalink: /:collection/:name
    name: Specifications
  doc:
    output: true
    permalink: /:collection/:name
    name: Documentation
  posts:
    output: true
    permalink: /news/:year/:month/:day/:slug
    name: News
    slug: news

include:
  - _redirects
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
